version: "3"
services:

  #  db-data:

  mymongodb:
    image: mongo:6.0.2
    container_name: MongoDbYenlo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password


  mongo-express:
    image: mongo-express
    container_name: MongoExpressYenlo
    depends_on:
      - mymongodb
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mymongodb:27017/